name: Build and test

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: make script executable
        run: chmod u+x build.sh
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
      - name: make script executable
        run: chmod u+x build.sh
      - name: Build Docs
        working-directory: ./
        run: ./build.sh builddocs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output # The folder the action should deploy.